services:
  - type: web
    name: engmate
    runtime: docker
    plan: free
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: Authentication__Google__ClientId
        sync: false
      - key: Authentication__Google__ClientSecret
        sync: false
